name=input('姓名：')
Hours_Worked=int(input('工作时长：'))
pay_hour=int(input('每小时收入：'))
rate=float(input('税率：'))
yljbl=float(input('养老金比例：'))
salary=Hours_Worked*pay_hour
print('Employee Name：'+name+'\n')
print('Hours Worked：'+str(Hours_Worked))
print('Pay Rate：$'+str(pay_hour))
print('Gross Pay：$'+str(salary))
print('Deductions：$'+str(salary*yljbl+salary*rate))
print('Net Pay：$'+str(salary-salary*rate-salary*yljbl))